### PR TITLE
Initialize `_session` member on YouTube controller

### PR DESCRIPTION
**Pull request by alexdelorenzo**
Fixes this error:

```bash
    youtube.quick_play(media_id=video_id, timeout=timeout)                                                                               
  File "~/.pyenv/versions/3.12.4/lib/python3.12/site-packages/pychromecast/controllers/youtube.py", line 182, in quick_play
    self.play_video(media_id, playlist_id=playlist_id, **kwargs)                                                                    
  File "~/.pyenv/versions/3.12.4/lib/python3.12/site-packages/pychromecast/controllers/youtube.py", line 104, in play_video
    self.start_session_if_none()
  File "~/.pyenv/versions/3.12.4/lib/python3.12/site-packages/pychromecast/controllers/youtube.py", line 92, in start_sessi
on_if_none
    if not (self._screen_id and self._session):
                                ^^^^^^^^^^^^^
AttributeError: 'YouTubeController' object has no attribute '_session'
```

### CODE REVIEW

**Review by elupus — APPROVED** [review]
Looks good

**Review by emontnemery — COMMENTED** [review]
~~I'm not sure this is the right solution, because we don't check `_session` for `None` anywhere~~

Edit: I broke this in https://github.com/home-assistant-libs/pychromecast/pull/816, sorry about  that and thanks for the fix @alexdelorenzo 👍
